---
- name: start php-fpm
  service:
    name: php-fpm
    state: started
- name: stop php-fpm
  service:
    name: php-fpm
    state: stoped
- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted
- name: reload php-fpm
  service:
    name: php-fpm
    state: reloaded
