---
- name: start apache
  service:
    name: httpd
    state: started
- name: stop apache
  service:
    name: httpd
    state: stoped
- name: restart apache
  service:
    name: httpd
    state: restarted
- name: reload apache
  service:
    name: httpd
    state: reloaded
