---
- name: start tomcat
  service:
    name: tomcat
    state: started
- name: stop tomcat
  service:
    name: tomcat
    state: stoped
- name: restart tomcat
  service:
    name: tomcat
    state: restarted
- name: reload tomcat
  service:
    name: tomcat
    state: reloaded
